build:
  maxIssues: 0

naming:
  FunctionNaming:
    ignoreAnnotated: ['Test', 'Composable']

style:
  MagicNumber:
    ignorePropertyDeclaration: true
  UnusedPrivateMember:
    ignoreAnnotated: ['Preview']

complexity:
  LongParameterList:
    ignoreAnnotated: ['Composable']
  LongMethod:
    ignoreAnnotated: ['Composable']